# Subject data for the AsciiDocsy theme
# You almost certainly don't need this file in your implementation
- app: Asciidoctor
  use: THE AsciiDoc markup converter
  url: https://www.asciidoctor.org
  git: https://github.com/asciidoctor/asciidoctor
  vrsn: '2.0'
- app: Jekyll
  use: world-class static-site generator (SSG)
  url: https://jekyllrb.com
  git: https://github.com/jekyll/jekyll
  vrsn: '4.0'
- app: Liquid
  use: Shopify's fierce templating lang & engine
  url: https://shopify.github.io/liquid/
  git: https://github.com/Shopify/liquid
- app: FontAwesome
  use: simple, elegant icons as a typeface
  url: https://fontawesome.com
  vrsn: '4.7'
- app: Bootstrap
  use: premiere HTML/CSS/JS framework
  url: https://getbootstrap.com
  git: https://github.com/twbs/bootstrap
  vrsn: '5'
- app: jQuery
  use: JavaScript framework
  url: https://jquery.com
  git: https://github.com/jquery/jquery
  vrsn: '3'
- app: Algolia
  use: search indexing and queries via REST
  url: https://www.algolia.com
  git: https://github.com/algolia/jekyll-algolia
- app: Netlify
  use: CI/CD for docs, hosting for static sites
  url: https://www.netlify.com
